function Hd = FIR_Constr_Least_squares_Bandpass(fs , n , fc1 , fc2)
%FIR_CONSTR_LEAST_SQUARES_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 20-Dec-2018 17:35:16

% FIR constrained least-squares Bandpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N       = n;    % Order
Fc1     = fc1;   % First Cutoff Frequency
Fc2     = fc2;  % Second Cutoff Frequency
Dstop1U = 1;    % Upper Stopband Attenuation
Dstop1L = 1;    % Lower Stopband Attenuation
DpassU  = 1;    % Upper Passband Ripple
DpassL  = 1;    % Lower Passband Ripple
Dstop2U = 1;    % Upper Stopband Attenuation
Dstop2L = 1;    % Lower Stopband Attenuation

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc1 Fc2 Fs/2]/(Fs/2), [0 1 0], [Dstop1U 1+DpassU ...
            Dstop2U], [-Dstop1L 1-DpassL -Dstop2L]);
Hd = dfilt.dffir(b);

% [EOF]
