function Hd = FIR_Constr_band_equiripple_Highpass(fs , n , fstop , fpass)
%FIR_CONSTR_BAND_EQUIRIPPLE_HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 20-Dec-2018 18:28:16

% Constrained Band Equiripple FIR Highpass filter designed using the
% FIRCBAND function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N     = n;   % Order
Fstop = fstop;  % Stopband Frequency
Fpass = fpass;  % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 1;     % Passband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRCBAND function.
b  = fircband(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass], ...
              {dens});
Hd = dfilt.dffir(b);

% [EOF]
