function Hd = FIR_Generalized_equiripple_Lowpass(fs , n , fpass , fstop)
%FIR_GENERALIZED_EQUIRIPPLE_LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 20-Dec-2018 18:13:34

% Generalized REMEZ FIR Lowpass filter designed using the FIRGR function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N     = n;   % Order
Fpass = fpass;  % Passband Frequency
Fstop = fstop;  % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 1;     % Stopband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
