function Hd = FIR_Constr_Least_squares_Highpass(fs , n , fc)
%FIR_CONSTR_LEAST_SQUARES_HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 20-Dec-2018 18:29:22

% FIR constrained least-squares Highpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N      = n;   % Order
Fc     = fc;  % Cutoff Frequency
DstopU = 0.1;   % Upper Stopband Attenuation
DstopL = 0.1;   % Lower Stopband Attenuation
DpassU = 0.1;   % Upper Passband Ripple
DpassL = 0.1;   % Lower Passband Ripple

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc Fs/2]/(Fs/2), [0 1], [DstopU 1+DpassU], [-DstopL ...
            1-DpassL]);
Hd = dfilt.dffir(b);

% [EOF]
