function Hd = IIR_Chebyshev_type_2_Bandpass(fs , n , fc1 , fc2)
%IIR_CHEBYSHEV_TYPE_2_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 20-Dec-2018 18:00:01

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N      = n;    % Order
Fstop1 = fc1;   % First Stopband Frequency
Fstop2 = fc2;  % Second Stopband Frequency
Astop  = 80;     % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
