function Hd = IIR_Chebyshev_type_1_Bandpass(fs , n , fc1 , fc2)
%IIR_CHEBYSHEV_TYPE_1_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 20-Dec-2018 17:58:43

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N      = n;    % Order
Fpass1 = fc1;   % First Passband Frequency
Fpass2 = fc2;  % Second Passband Frequency
Apass  = 1;      % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');

% [EOF]
